export const environment = {
  production: false,
  debug: true,
  api: 'https://api-desarrollo.cns.gob.bo',
  erpCnsApi: 'https://api-desarrollo.cns.gob.bo/erpcns',
  reportesApi: 'https://localhost:6002',
  apiVersion: 'v1',
  apiSecurity: 'https://api-desarrollo.cns.gob.bo/catalogo',
  notificationURI: 'https://api-desarrollo.cns.gob.bo/almacenes',
  apiAuth: 'https://api-desarrollo.cns.gob.bo/auth',
  staticMenu: false,
  issuer: 'https://auth-desarrollo.cns.gob.bo',
  clientId: 'test_dev',
  responseType: 'code',
  redirectUri: '/auth-callback',
  silentRefreshRedirectUri: '/silent-refresh.html',
  scope: 'openid profile offline_access API_Example api.read adminClient_api',
  postLogoutRedirectUri: '/login',
  useSilentRefresh: false,
  sessionChecksEnabled: false,
  showDebugInformation: false,
  clearHashAfterLogin: false,
  nonceStateSeparator: 'semicolon',  
  citaMedicaApi: 'https://api-desarrollo.cns.gob.bo/api/ct',
  vigenciaApi: 'https://api-desarrollo.cns.gob.bo/api/vg',
  laboratorioApi: 'https://api-desarrollo.cns.gob.bo/api/lab',
  lisApi: 'http://localhost:5000/api/',
  theme: 'layout-cns-nacional',
  version: 'dev-local',
  deployDate: 'local',
}
